ru:
  nklsfnv:
    bot:
      name:
      token:

igdb:
  timeout_value: 5
  api:
    root_uri: "https://api.igdb.com/v4"
    client_id:
    client_secret:
  twitch:
    auth_uri: "https://id.twitch.tv/oauth2/token"
    auth_default_grant_type: client_credentials
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/nklsfnvbot
    username: nklsfnvbot
    password: 123
  liquibase:
    change-log: classpath:liquibase/migration.yml
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

server:
  port: 8082