ru:
  nklsfnv:
    bot:
      name:
      token:
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/nklsfnvbot
    username: nklsfnvbot
    password: 123
  liquibase:
    change-log: classpath:liquibase/migration.yml
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true